// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-bond/bond (interfaces: Filter,FilterStorer,TableScanner)
//
// Generated by this command:
//
//	mockgen -destination ./mock/bond/bond.go -package bondmock github.com/go-bond/bond Filter,FilterStorer,TableScanner
//

// Package bondmock is a generated GoMock package.
package bondmock

import (
	context "context"
	io "io"
	reflect "reflect"

	bond "github.com/go-bond/bond"
	gomock "go.uber.org/mock/gomock"
)

// MockFilter is a mock of Filter interface.
type MockFilter struct {
	ctrl     *gomock.Controller
	recorder *MockFilterMockRecorder
	isgomock struct{}
}

// MockFilterMockRecorder is the mock recorder for MockFilter.
type MockFilterMockRecorder struct {
	mock *MockFilter
}

// NewMockFilter creates a new mock instance.
func NewMockFilter(ctrl *gomock.Controller) *MockFilter {
	mock := &MockFilter{ctrl: ctrl}
	mock.recorder = &MockFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilter) EXPECT() *MockFilterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFilter) Add(ctx context.Context, key []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", ctx, key)
}

// Add indicates an expected call of Add.
func (mr *MockFilterMockRecorder) Add(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFilter)(nil).Add), ctx, key)
}

// Clear mocks base method.
func (m *MockFilter) Clear(ctx context.Context, store bond.FilterStorer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockFilterMockRecorder) Clear(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockFilter)(nil).Clear), ctx, store)
}

// Load mocks base method.
func (m *MockFilter) Load(ctx context.Context, store bond.FilterStorer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockFilterMockRecorder) Load(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockFilter)(nil).Load), ctx, store)
}

// MayContain mocks base method.
func (m *MockFilter) MayContain(ctx context.Context, key []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MayContain", ctx, key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// MayContain indicates an expected call of MayContain.
func (mr *MockFilterMockRecorder) MayContain(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MayContain", reflect.TypeOf((*MockFilter)(nil).MayContain), ctx, key)
}

// RecordFalsePositive mocks base method.
func (m *MockFilter) RecordFalsePositive() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordFalsePositive")
}

// RecordFalsePositive indicates an expected call of RecordFalsePositive.
func (mr *MockFilterMockRecorder) RecordFalsePositive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFalsePositive", reflect.TypeOf((*MockFilter)(nil).RecordFalsePositive))
}

// Save mocks base method.
func (m *MockFilter) Save(ctx context.Context, store bond.FilterStorer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, store)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockFilterMockRecorder) Save(ctx, store any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockFilter)(nil).Save), ctx, store)
}

// Stats mocks base method.
func (m *MockFilter) Stats() bond.FilterStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(bond.FilterStats)
	return ret0
}

// Stats indicates an expected call of Stats.
func (mr *MockFilterMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockFilter)(nil).Stats))
}

// MockFilterStorer is a mock of FilterStorer interface.
type MockFilterStorer struct {
	ctrl     *gomock.Controller
	recorder *MockFilterStorerMockRecorder
	isgomock struct{}
}

// MockFilterStorerMockRecorder is the mock recorder for MockFilterStorer.
type MockFilterStorerMockRecorder struct {
	mock *MockFilterStorer
}

// NewMockFilterStorer creates a new mock instance.
func NewMockFilterStorer(ctrl *gomock.Controller) *MockFilterStorer {
	mock := &MockFilterStorer{ctrl: ctrl}
	mock.recorder = &MockFilterStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterStorer) EXPECT() *MockFilterStorerMockRecorder {
	return m.recorder
}

// DeleteRange mocks base method.
func (m *MockFilterStorer) DeleteRange(start, end []byte, opt bond.WriteOptions, batch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{start, end, opt}
	for _, a := range batch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRange", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRange indicates an expected call of DeleteRange.
func (mr *MockFilterStorerMockRecorder) DeleteRange(start, end, opt any, batch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{start, end, opt}, batch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRange", reflect.TypeOf((*MockFilterStorer)(nil).DeleteRange), varargs...)
}

// Get mocks base method.
func (m *MockFilterStorer) Get(key []byte, batch ...bond.Batch) ([]byte, io.Closer, error) {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range batch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(io.Closer)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockFilterStorerMockRecorder) Get(key any, batch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, batch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFilterStorer)(nil).Get), varargs...)
}

// Set mocks base method.
func (m *MockFilterStorer) Set(key, value []byte, opt bond.WriteOptions, batch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{key, value, opt}
	for _, a := range batch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockFilterStorerMockRecorder) Set(key, value, opt any, batch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key, value, opt}, batch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockFilterStorer)(nil).Set), varargs...)
}

// MockTableScanner is a mock of TableScanner interface.
type MockTableScanner[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockTableScannerMockRecorder[T]
	isgomock struct{}
}

// MockTableScannerMockRecorder is the mock recorder for MockTableScanner.
type MockTableScannerMockRecorder[T any] struct {
	mock *MockTableScanner[T]
}

// NewMockTableScanner creates a new mock instance.
func NewMockTableScanner[T any](ctrl *gomock.Controller) *MockTableScanner[T] {
	mock := &MockTableScanner[T]{ctrl: ctrl}
	mock.recorder = &MockTableScannerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableScanner[T]) EXPECT() *MockTableScannerMockRecorder[T] {
	return m.recorder
}

// Scan mocks base method.
func (m *MockTableScanner[T]) Scan(ctx context.Context, tr *[]T, reverse bool, optBatch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tr, reverse}
	for _, a := range optBatch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockTableScannerMockRecorder[T]) Scan(ctx, tr, reverse any, optBatch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tr, reverse}, optBatch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockTableScanner[T])(nil).Scan), varargs...)
}

// ScanForEach mocks base method.
func (m *MockTableScanner[T]) ScanForEach(ctx context.Context, f func(bond.KeyBytes, bond.Lazy[T]) (bool, error), reverse bool, optBatch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, f, reverse}
	for _, a := range optBatch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanForEach", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanForEach indicates an expected call of ScanForEach.
func (mr *MockTableScannerMockRecorder[T]) ScanForEach(ctx, f, reverse any, optBatch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, f, reverse}, optBatch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanForEach", reflect.TypeOf((*MockTableScanner[T])(nil).ScanForEach), varargs...)
}

// ScanIndex mocks base method.
func (m *MockTableScanner[T]) ScanIndex(ctx context.Context, i *bond.Index[T], s bond.Selector[T], tr *[]T, reverse bool, optBatch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, i, s, tr, reverse}
	for _, a := range optBatch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanIndex", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanIndex indicates an expected call of ScanIndex.
func (mr *MockTableScannerMockRecorder[T]) ScanIndex(ctx, i, s, tr, reverse any, optBatch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, i, s, tr, reverse}, optBatch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanIndex", reflect.TypeOf((*MockTableScanner[T])(nil).ScanIndex), varargs...)
}

// ScanIndexForEach mocks base method.
func (m *MockTableScanner[T]) ScanIndexForEach(ctx context.Context, idx *bond.Index[T], s bond.Selector[T], f func(bond.KeyBytes, bond.Lazy[T]) (bool, error), reverse bool, optBatch ...bond.Batch) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, idx, s, f, reverse}
	for _, a := range optBatch {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanIndexForEach", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanIndexForEach indicates an expected call of ScanIndexForEach.
func (mr *MockTableScannerMockRecorder[T]) ScanIndexForEach(ctx, idx, s, f, reverse any, optBatch ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, idx, s, f, reverse}, optBatch...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanIndexForEach", reflect.TypeOf((*MockTableScanner[T])(nil).ScanIndexForEach), varargs...)
}
